// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace icream.Models
{
    [Table("Category")]
    public partial class Category
    {
        public Category()
        {
            Galleries = new HashSet<Gallery>();
        }

        [Key]
        public int id { get; set; }
        [StringLength(50)]
        public string name { get; set; }

        [InverseProperty("category")]
        public virtual ICollection<Gallery> Galleries { get; set; }
    }
}