// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace icream.Models
{
    public partial class Chef
    {
        [Key]
        public int id { get; set; }
        [StringLength(100)]
        public string name { get; set; }
        [StringLength(50)]
        public string job_name { get; set; }
        [Column(TypeName = "image")]
        public byte[] image { get; set; }
        [StringLength(500)]
        public string facebook_link { get; set; }
        [StringLength(500)]
        public string twitter_link { get; set; }
        [StringLength(500)]
        public string linkedin_link { get; set; }
    }
}