// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace icream.Models
{
    public partial class Contact
    {
        [Key]
        public int id { get; set; }
        [StringLength(200)]
        public string subject { get; set; }
        [StringLength(900)]
        public string message { get; set; }
        public int? user_id { get; set; }

        [ForeignKey("user_id")]
        [InverseProperty("Contacts")]
        public virtual User user { get; set; }
    }
}